[package]
name = "kos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kosalt = "3.1.3"
rand = "0.8.5"
serde_json = "1.0.99"
